#!/usr/bin/env bash
#
# last_verified: 2026-09-26 · tetragon n/a
#
# Build a Tetragon file-access tracing policy from a small argument list.
#
# The first policy I applied by hand (first-tracing-policy-exec-file.yaml) only
# watched exec events, and it was enough to confirm Tetragon was producing
# output. For file-access tracing I wanted something I could re-run with a
# different path without hand-editing YAML, so this script renders the policy
# from arguments instead.
#
# Usage:
#   ./build-tetragon-file-access-tracing-policy.sh \
#       --policy-name file-watch-web-files \
#       --path "/var/log/nginx" \
#       --output /tmp/file-watch.yaml

set -uo pipefail

usage() {
  cat <<EOF
Usage: $0 --policy-name <name> --path <path> [--output <file>] [--help]

Renders a cilium.io/v1alpha1 TracingPolicy that traces file-access events on
the given path. The policy is observe-only (no enforcement), so it is safe to
apply on a shared cluster.
EOF
}

die() {
  echo "build-tetragon-file-access-tracing-policy: $*" >&2
  exit 1
}

POLICY_NAME=""
PATH_TO_WATCH=""
OUTPUT=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --policy-name) POLICY_NAME="${2:-}"; shift 2 ;;
    --path)        PATH_TO_WATCH="${2:-}"; shift 2 ;;
    --output)      OUTPUT="${2:-}"; shift 2 ;;
    --help|-h)     usage; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

[ -n "$POLICY_NAME" ] || die "--policy-name is required"
[ -n "$PATH_TO_WATCH" ] || die "--path is required"

# Normalise the path so the generated selector is unambiguous.
case "$PATH_TO_WATCH" in
  /*) : ;;
  *)  PATH_TO_WATCH="/$PATH_TO_WATCH" ;;
esac

cat <<EOF
# Generated by build-tetragon-file-access-tracing-policy.sh
# last_verified: 2026-09-26 · tetragon n/a
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: ${POLICY_NAME}
  annotations:
    tetragon.io/description: "Trace file-access events on ${PATH_TO_WATCH}"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    args:
    - index: 0
      type: "file"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - "${PATH_TO_WATCH}"
EOF

if [ -n "$OUTPUT" ]; then
  echo "Wrote policy to ${OUTPUT}"
fi